version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: social_media
      MYSQL_USER: murali
      MYSQL_PASSWORD: murali
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:

